### ISSUE TITLE
4.0.1 `npx sandbox` tries to copy file over itself, fails, 

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#164]
`C:\Users\mikem\OneDrive\Documents\testapp\src\shared\readme.md` is being copied to itself:

    testapp $ npx sandbox
                                                                
            ARC_APP_NAME testapp                                 
              AWS_REGION us-west-2                               
            AWS_PROFILE xxx                                     
                                                                
                    Node 8.12.0                                  
                    npm 6.4.0                                   
                    .arc 4.0.1                                   
                                                                
    ✓ @tables created in local database
    C:\Users\mikem\OneDrive\Documents\testapp\node_modules\aws-sdk\lib\request.js:31
                throw err;
                ^

    Error: EBUSY: resource busy or locked, copyfile 'C:\Users\mikem\OneDrive\Documents\testapp\src\shared\read
    me.md' -> 'C:\Users\mikem\OneDrive\Documents\testapp\src\shared\readme.md'
        at Object.fs.copyFileSync (fs.js:1918:11)
        at paths.forEach.pathToCode (C:\Users\mikem\OneDrive\Documents\testapp\node_modules\@architect\archite
    ct\src\sandbox\env\_copy-shared.js:27:12)
        at Array.forEach (<anonymous>)
        at files.forEach.f (C:\Users\mikem\OneDrive\Documents\testapp\node_modules\@architect\architect\src\sa
    ndbox\env\_copy-shared.js:19:11)
        at Array.forEach (<anonymous>)
        at Array._shared (C:\Users\mikem\OneDrive\Documents\testapp\node_modules\@architect\architect\src\sand
    box\env\_copy-shared.js:18:9)
        at runSeries (C:\Users\mikem\OneDrive\Documents\testapp\node_modules\run-series\index.js:22:33)
        at env (C:\Users\mikem\OneDrive\Documents\testapp\node_modules\@architect\architect\src\sandbox\env\in
    dex.js:7:3)
        at Array._env (C:\Users\mikem\OneDrive\Documents\testapp\node_modules\@architect\architect\src\sandbox
    \start.js:30:7)
        at each (C:\Users\mikem\OneDrive\Documents\testapp\node_modules\run-series\index.js:19:24)

**Comment by ryanblock** [comment]
Interesting. Can you post your `.arc` manifest? Do you have any functions set up?

**Comment by mikemaccana** [comment]
`.arc` is from https://blog.begin.com/introducing-architect-4-0-faster-lighter-simpler-serverless-59f6dc156bf2 

    @app
    testapp

    @http
    get /

**Comment by ryanblock** [comment]
Sounds like a Windows boog, we're looking into it!

**Comment by brianleroux** [comment]
Sorry about that; should have done more testing on Windows. Thx for sticking w us through these rough bits.
