### ISSUE TITLE
InvalidParameterType from aws-sdk during `deploy` on arc 4.4.4

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/architect#226]
**Describe the bug**

**To Reproduce**

`npx deploy` on architect 4.4.4 generates a bunch of aws-sdk errors similar to the one below:

```
`-- @architect/architect@4.4.4
  `-- aws-sdk@2.372.0
```

This wasn't happening on earlier arc versions. 

    { InvalidParameterType: Expected params.ContentType to be a string
        at ParamValidator.fail (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\param_validator.js:50:37)
        at ParamValidator.validateType (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\param_validator.js:232:10)
        at ParamValidator.validateString (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\param_validator.js:154:32)
        at ParamValidator.validateScalar (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\param_validator.js:130:21)
        at ParamValidator.validateMember (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\param_validator.js:94:21)
        at ParamValidator.validateStructure (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\param_validator.js:75:14)
        at ParamValidator.validateMember (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\param_validator.js:88:21)
        at ParamValidator.validate (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\param_validator.js:34:10)
        at Request.VALIDATE_PARAMETERS (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\event_listeners.js:126:42)
        at Request.callListeners (C:\Users\mikem\OneDrive\Documents\myapp\myapp\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    message: 'Expected params.ContentType to be a string',
    code: 'InvalidParameterType',
    time: 2018-12-07T15:24:25.520Z }

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by brianleroux** [comment]
did downgrading fix?

**Comment by mikemaccana** [comment]
Checking now - the errors don't seem to stop the deploy though.

**Comment by mikemaccana** [comment]
(Talking to myself here). OK hard to tell if reverting helped, it may be a recent change to routes that's affecting things. Reverting those....




```
Checking if false is a string
{ InvalidParameterType: Expected params.ContentType to be a string
    at ParamValidator.fail (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\param_validator.js:52:35)
    at ParamValidator.validateType (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\param_validator.js:289:8)
    at ParamValidator.validateString (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\param_validator.js:171:30)
    at ParamValidator.validateScalar (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\param_validator.js:142:17)
    at ParamValidator.validateMember (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\param_validator.js:100:17)
    at ParamValidator.validateStructure (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\param_validator.js:79:10)
    at ParamValidator.validateMember (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\param_validator.js:94:17)
    at ParamValidator.validate (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\param_validator.js:34:8)
    at Request.VALIDATE_PARAMETERS (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\event_listeners.js:126:42)
    at Request.callListeners (C:\Users\mikem\OneDrive\Documents\serverless-commerce\serverless-commerce\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
  message: 'Expected params.ContentType to be a string',
  code: 'InvalidParameterType',
  time: 2018-12-07T18:38:48.665Z }```

**Comment by mikemaccana** [comment]
OK got a good version, going to do a git bisect and find out where I triggered this. Probaby me not arc, but will leave open while I figure it out.
