### ISSUE TITLE
repl does not load local environment variables if NODE_ENV != testing

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/architect#271]
**Describe the bug**
`repl` (used for directly accessing the data layer with `@architect/data`) does not load `.arc-env` if NODE_ENV != testing.

This means `repl` can't be used with `NODE_ENV=staging` to access live remote DBs.

**To Reproduce**
1. Run `NODE_ENV=staging npx repl` or `NODE_ENV=staging ARC_LOCAL=1 npx repl`
2. Attempt to access a table (e.g. `data.whatever.scan({})`
3. Credentials error is output:
```
#!/data> (node:22909) UnhandledPromiseRejectionWarning: UnrecognizedClientException: The security token included in the request is invalid.
    at Request.extractError (/project/path/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/project/path/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/project/path/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/project/path/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/project/path/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/project/path/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /project/path/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/project/path/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/project/path/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/project/path/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:22909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Expected behavior**
`repl` should load `.arc-env` env vars locally if NODE_ENV != testing and use them for remote db access

**Comment by ryanblock** [comment]
Fixed in `5.0.4`
