### ISSUE TITLE
Creating multiple secondary indexes at the same time fails

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/architect#334]
**To Reproduce**
1. Create a new table with `@tables`
2. Specify multiple `@indexes`
3. A secondary index will fail with the following error, and won't succeed until the index is completed

**Error**
```
{ LimitExceededException: Subscriber limit exceeded: Only 1 online index can be created or deleted simultaneously per table
    at Request.extractError ($projectPath/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners ($projectPath/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit ($projectPath/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit ($projectPath/aws-sdk/lib/request.js:683:14)
    at Request.transition ($projectPath/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo ($projectPath/aws-sdk/lib/state_machine.js:14:12)
    at $projectPath/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> ($projectPath/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> ($projectPath/aws-sdk/lib/request.js:685:12)
    at Request.callListeners ($projectPath/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Subscriber limit exceeded: Only 1 online index can be created or deleted simultaneously per table',
  code: 'LimitExceededException',
  time: 2019-03-15T22:31:29.879Z,
  requestId: 'EA3H4BR5LC8PLBNT7IPE482MDNVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
```

**Comment by ryanblock** [comment]
Dupe of https://github.com/arc-repos/architect/issues/268
