### ISSUE TITLE
Expanding the number of lines returned in stack trace.

### ISSUE THREAD

**Issue by jonathanstiansen** [arc-repos/architect#359]
Might be too uncommon, so feel free to close it.

I can't reproduce this on a new project, so it's definitely an edge case but it would be good if stack traces were longer so that if the call stack is large, we'll still see the the pieces of our code that caused the issue.

```
TypeError: Cannot read property 'map' of undefined
    at _public (/Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/@architect/architect/src/sandbox/http/fallback.js:22:25)
    at Layer.handle [as handle_request] (/Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/router/lib/layer.js:93:5)
    at trim_prefix (/Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/router/index.js:335:13)
    at /Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/router/index.js:299:7
    at Function.process_params (/Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/router/index.js:354:12)
    at next (/Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/router/index.js:290:10)
    at _public (/Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/@architect/architect/src/sandbox/http/public-middleware.js:13:5)
    at Layer.handle [as handle_request] (/Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/router/lib/layer.js:93:5)
    at trim_prefix (/Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/router/index.js:335:13)
    at /Users/jono/projects/philia_contracts/worknicer/worknicer/node_modules/router/index.js:299:7
```

**Comment by ryanblock** [comment]
Have noticed this more acutely when business logic level issues cause `aws-sdk` issues, the result is an `aws-sdk` stack trace that often may not refer to the caller. Would love to figure out if we can expand this!

**Comment by brianleroux** [comment]
this is probably a 'solve w patience' situation… an improved aws-sdk v3 should help narrow these issues https://github.com/aws/aws-sdk-js-v3 (tho if you use async/await and promise it won't help stack traces)

**Comment by jonathanstiansen** [comment]
I don't think I quite understand - are you saying if we use the new SDK it will just work?

**Comment by brianleroux** [comment]
Ah, no sorry that was confusing. Saying that future versions of the SDK once stable will narrow down problems.
